/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { initializeApp, getApps, FirebaseApp } from 'firebase/app';
import { 
  getFirestore, 
  collection, 
  doc, 
  setDoc, 
  deleteDoc,
  onSnapshot, 
  getDocs, 
  writeBatch,
  Firestore,
  Unsubscribe
} from 'firebase/firestore';
import { Student, Teacher, SavedPin, SchoolSettings } from '../types';

let app: FirebaseApp | null = null;
let db: Firestore | null = null;
let isFirebaseInitialized = false;

// Attempt to load Firebase configuration dynamically from /firebase-applet-config.json
// or fallback to predefined environment variables
export async function initFirebaseService(onReady: (active: boolean) => void) {
  try {
    // Check environment variables first
    const metaEnv = (import.meta as any).env || {};
    const envConfig = {
      apiKey: metaEnv.VITE_FIREBASE_API_KEY,
      authDomain: metaEnv.VITE_FIREBASE_AUTH_DOMAIN,
      projectId: metaEnv.VITE_FIREBASE_PROJECT_ID,
      storageBucket: metaEnv.VITE_FIREBASE_STORAGE_BUCKET,
      messagingSenderId: metaEnv.VITE_FIREBASE_MESSAGING_SENDER_ID,
      appId: metaEnv.VITE_FIREBASE_APP_ID,
    };

    let finalConfig: any = null;

    if (envConfig.apiKey && envConfig.projectId) {
      finalConfig = envConfig;
    } else {
      // Try to fetch public/firebase-applet-config.json which is generated by the AI Studio platform
      const response = await fetch('/firebase-applet-config.json');
      if (response.ok) {
        finalConfig = await response.json();
      }
    }

    if (finalConfig && finalConfig.apiKey && finalConfig.projectId) {
      if (getApps().length === 0) {
        app = initializeApp(finalConfig);
      } else {
        app = getApps()[0];
      }
      
      // Use custom firestore database ID if specified in configuration
      if (finalConfig.firestoreDatabaseId) {
        db = getFirestore(app, finalConfig.firestoreDatabaseId);
      } else {
        db = getFirestore(app);
      }
      
      isFirebaseInitialized = true;
      console.log('Firebase synced and initialized successfully on port 3000');
      onReady(true);
      return true;
    }
  } catch (error) {
    console.warn('Firebase setup is pending or in Local Fallback mode:', error);
  }
  
  isFirebaseInitialized = false;
  onReady(false);
  return false;
}

export function isFirebaseReady(): boolean {
  return isFirebaseInitialized && db !== null;
}

export enum OperationType {
  CREATE = 'create',
  UPDATE = 'update',
  DELETE = 'delete',
  LIST = 'list',
  GET = 'get',
  WRITE = 'write',
}

interface FirestoreErrorInfo {
  error: string;
  operationType: OperationType;
  path: string | null;
  authInfo: {
    userId: string | null;
  };
}

function handleFirestoreError(error: unknown, operationType: OperationType, path: string | null) {
  const errInfo: FirestoreErrorInfo = {
    error: error instanceof Error ? error.message : String(error),
    authInfo: {
      userId: 'anonymous'
    },
    operationType,
    path
  };
  console.error('Firestore Error: ', JSON.stringify(errInfo));
  throw new Error(JSON.stringify(errInfo));
}

/**
 * Register a new school workspace in Firestore.
 * It will create the settings document and the default admin pin document.
 */
export async function dbCreateSchoolWorkspace(schoolId: string, settings: SchoolSettings, adminPin: SavedPin): Promise<boolean> {
  if (!db) return false;
  try {
    // 1. Create school settings
    await setDoc(doc(db, 'schools', schoolId, 'settings', 'school'), settings);
    // 2. Create the initial admin PIN
    await setDoc(doc(db, 'schools', schoolId, 'pins', adminPin.id), adminPin);
    return true;
  } catch (error) {
    handleFirestoreError(error, OperationType.WRITE, `schools/${schoolId}/setup`);
    return false;
  }
}

/**
 * Fetch school settings once (for login/verification)
 */
export async function dbFetchSchoolSettingsOnce(schoolId: string): Promise<SchoolSettings | null> {
  if (!db) return null;
  try {
    const docSnap = await getDocs(collection(db, 'schools', schoolId, 'settings'));
    let found: SchoolSettings | null = null;
    docSnap.forEach((doc) => {
      if (doc.id === 'school') {
        found = doc.data() as SchoolSettings;
      }
    });
    return found;
  } catch (error) {
    console.warn('Error fetching school settings once:', error);
    return null;
  }
}

/**
 * Fetch all PINs for a school once
 */
export async function dbFetchSchoolPinsOnce(schoolId: string): Promise<SavedPin[]> {
  if (!db) return [];
  try {
    const pinsSnap = await getDocs(collection(db, 'schools', schoolId, 'pins'));
    const list: SavedPin[] = [];
    pinsSnap.forEach((doc) => {
      list.push(doc.data() as SavedPin);
    });
    return list;
  } catch (error) {
    console.warn('Error fetching school PINs once:', error);
    return [];
  }
}

/**
 * Sync School Settings document in real-time
 */
export function subscribeToSchoolSettings(schoolId: string, onUpdate: (settings: SchoolSettings) => void): Unsubscribe | null {
  if (!db) return null;
  return onSnapshot(doc(db, 'schools', schoolId, 'settings', 'school'), (snapshot) => {
    if (snapshot.exists()) {
      onUpdate(snapshot.data() as SchoolSettings);
    }
  }, (error) => {
    handleFirestoreError(error, OperationType.GET, `schools/${schoolId}/settings/school`);
  });
}

/**
 * Save School Settings
 */
export async function dbSaveSchoolSettings(schoolId: string, settings: SchoolSettings) {
  if (!db) return false;
  try {
    await setDoc(doc(db, 'schools', schoolId, 'settings', 'school'), settings);
    return true;
  } catch (error) {
    handleFirestoreError(error, OperationType.WRITE, `schools/${schoolId}/settings/school`);
    return false;
  }
}

/**
 * Sync Students collection in real-time
 */
export function subscribeToStudents(schoolId: string, onUpdate: (students: Student[]) => void): Unsubscribe | null {
  if (!db) return null;
  return onSnapshot(collection(db, 'schools', schoolId, 'students'), (snapshot) => {
    const list: Student[] = [];
    snapshot.forEach((doc) => {
      list.push(doc.data() as Student);
    });
    onUpdate(list);
  }, (error) => {
    handleFirestoreError(error, OperationType.LIST, `schools/${schoolId}/students`);
  });
}

/**
 * Sync Teachers collection in real-time
 */
export function subscribeToTeachers(schoolId: string, onUpdate: (teachers: Teacher[]) => void): Unsubscribe | null {
  if (!db) return null;
  return onSnapshot(collection(db, 'schools', schoolId, 'teachers'), (snapshot) => {
    const list: Teacher[] = [];
    snapshot.forEach((doc) => {
      list.push(doc.data() as Teacher);
    });
    onUpdate(list);
  }, (error) => {
    handleFirestoreError(error, OperationType.LIST, `schools/${schoolId}/teachers`);
  });
}

/**
 * Sync Authorized PINs collection in real-time
 */
export function subscribeToPins(schoolId: string, onUpdate: (pins: SavedPin[]) => void): Unsubscribe | null {
  if (!db) return null;
  return onSnapshot(collection(db, 'schools', schoolId, 'pins'), (snapshot) => {
    const list: SavedPin[] = [];
    snapshot.forEach((doc) => {
      list.push(doc.data() as SavedPin);
    });
    onUpdate(list);
  }, (error) => {
    handleFirestoreError(error, OperationType.LIST, `schools/${schoolId}/pins`);
  });
}

/**
 * CRUD functions for Students
 */
export async function dbSaveStudent(schoolId: string, student: Student) {
  if (!db) return false;
  try {
    await setDoc(doc(db, 'schools', schoolId, 'students', student.id), student);
    return true;
  } catch (error) {
    handleFirestoreError(error, OperationType.WRITE, `schools/${schoolId}/students/${student.id}`);
    return false;
  }
}

export async function dbDeleteStudent(schoolId: string, id: string) {
  if (!db) return false;
  try {
    await deleteDoc(doc(db, 'schools', schoolId, 'students', id));
    return true;
  } catch (error) {
    handleFirestoreError(error, OperationType.DELETE, `schools/${schoolId}/students/${id}`);
    return false;
  }
}

/**
 * CRUD functions for Teachers
 */
export async function dbSaveTeacher(schoolId: string, teacher: Teacher) {
  if (!db) return false;
  try {
    await setDoc(doc(db, 'schools', schoolId, 'teachers', teacher.id), teacher);
    return true;
  } catch (error) {
    handleFirestoreError(error, OperationType.WRITE, `schools/${schoolId}/teachers/${teacher.id}`);
    return false;
  }
}

export async function dbDeleteTeacher(schoolId: string, id: string) {
  if (!db) return false;
  try {
    await deleteDoc(doc(db, 'schools', schoolId, 'teachers', id));
    return true;
  } catch (error) {
    handleFirestoreError(error, OperationType.DELETE, `schools/${schoolId}/teachers/${id}`);
    return false;
  }
}

/**
 * CRUD functions for PINs
 */
export async function dbSavePin(schoolId: string, pin: SavedPin) {
  if (!db) return false;
  try {
    await setDoc(doc(db, 'schools', schoolId, 'pins', pin.id), pin);
    return true;
  } catch (error) {
    handleFirestoreError(error, OperationType.WRITE, `schools/${schoolId}/pins/${pin.id}`);
    return false;
  }
}

export async function dbDeletePin(schoolId: string, id: string) {
  if (!db) return false;
  try {
    await deleteDoc(doc(db, 'schools', schoolId, 'pins', id));
    return true;
  } catch (error) {
    handleFirestoreError(error, OperationType.DELETE, `schools/${schoolId}/pins/${id}`);
    return false;
  }
}

/**
 * One-time data uploading (Migration from localStorage to Cloud Firestore)
 */
export async function uploadLocalDataToFirebase(schoolId: string, students: Student[], teachers: Teacher[], pins: SavedPin[]) {
  if (!db) return false;
  try {
    const batch = writeBatch(db);
    
    // Migrate students
    for (const s of students) {
      const docRef = doc(db, 'schools', schoolId, 'students', s.id);
      batch.set(docRef, s);
    }
    
    // Migrate teachers
    for (const t of teachers) {
      const docRef = doc(db, 'schools', schoolId, 'teachers', t.id);
      batch.set(docRef, t);
    }

    // Migrate pins
    for (const p of pins) {
      const docRef = doc(db, 'schools', schoolId, 'pins', p.id);
      batch.set(docRef, p);
    }
    
    await batch.commit();
    return true;
  } catch (error) {
    handleFirestoreError(error, OperationType.WRITE, `schools/${schoolId}/batch-migration`);
    return false;
  }
}
